Feature ermakov
rakovets/workshop-asciidoc pull request #13
Opened 2021-05-10 15:54 UTC by EvgeniErmakov

2021-05-10 22:44 UTC, ttokamo requested changes

2021-05-10 22:44 UTC, ttokamo commented on dir-example/Documenting the project.adoc
> +image::asciiErmakov.png[содержимое файла index.html]
> *Даем названия для изображений, что бы они отражали суть того, что на них изображено;
*Добавляем адекватный альтернативный текст для изображений.

Суть изображения не понять по его названию и альтернативному тексту

2021-05-11 09:51 UTC, rakovets reviewed
Патрэбна выправіць наступныя заўвагі.

2021-05-11 09:51 UTC, rakovets commented on index.adoc
> -= Theme
Патрэбна  змяніць на вашу тэму ("Maven")

2021-05-11 09:51 UTC, rakovets commented on index.adoc
> -Wiki for Git.
Напісаць што гэта `Wiki for Maven`

2021-05-11 09:51 UTC, rakovets commented on index.adoc
> -include::dir-example/page2.adoc[leveloffset=1]
Гэта патрбна замяніць на зробленную вамі старонку, але пры гэтым захаваць сінтаксіс

2021-05-11 09:51 UTC, rakovets commented on dir-example/Documenting the project.adoc
> +:imagesdir: ../assets/img/dir-example
`dir-example` - гэта дэрыкторыя для прыкладу, у вас жа канкрэтная тэма, пад якую патрэбна стварыць сваю дэрыкторую (`maven`)

2021-05-11 09:51 UTC, rakovets commented on dir-example/Documenting the project.adoc
> +В этом уроке мы изучим как создавать документацию проекта.
Выдаліць "ваду", г.зн. інфармацыю якая не неся ніякай карыснай інфармацыі

2021-05-11 09:51 UTC, rakovets commented on dir-example/Documenting the project.adoc
> +[source,shell script]
Дадаць пусты радок паміж кодам і звычайным параграфам

2021-05-12 09:36 UTC, Deimos1311 submitted a review, later dismissed

2021-05-12 11:19 UTC, davydovbv requested changes

2021-05-12 11:19 UTC, davydovbv commented on Maven.adoc
> +maven/creating-documentation-for-project.adoc
```suggestion
= Maven
:source-highlighter: prettify
:sectnums:
:toc: left
:toclevels: 1

:toc!:

Wiki for Maven.

include::maven/creating-documentation-for-project.adoc[leveloffset=1]

2021-05-12 11:19 UTC, davydovbv commented on Maven.adoc
> +maven/creating-documentation-for-project.adoc
This file should look like this

2021-05-12 11:26 UTC, davydovbv submitted a review, later dismissed

2021-05-12 11:29 UTC, rakovets requested changes
Патрэбна выправіць апісаныя ніжэй недахопы

2021-05-12 11:29 UTC, rakovets commented on Maven.adoc
> +include::maven/creating-documentation-for-project.adoc[leveloffset=1]
Чаму ты змяніў назву файла?
Гэтага не патрэбна рабіць, галоўная старонка для web: `index`. Таму зрабі для яго назву: `index.adoc`, а не `Maven.adoc`

2021-05-12 11:29 UTC, rakovets commented on maven/creating-documentation-for-project.adoc
> += Documenting the project
```suggestion
= Documenting the project
:imagesdir: ../assets/img/imagesMaven
```

2021-05-12 11:29 UTC, rakovets commented on maven/creating-documentation-for-project.adoc
> +
А навошта тут выдаліў што гэта source code?
```suggestion
[source, shell script]
```

2021-05-12 11:38 UTC, davydovbv approved these changes

2021-05-12 12:02 UTC, rakovets approved these changes
Approved

2021-05-12 12:07 UTC, Deimos1311 approved these changes

2021-05-12 12:09 UTC, ttokamo approved these changes

2021-05-12 12:34 UTC, merged