feauture-Kolesnik / it-academy / M-JC1-69-21 / Evgen Kolesnik / Maven
rakovets/workshop-asciidoc pull request #14
Opened 2021-05-12 08:20 UTC by Deimos1311

2021-05-12 11:22 UTC, rakovets requested changes
'Files changed' = 0
You need to do this task

2021-05-12 12:12 UTC, rakovets requested changes
Няправільае месцазнаходжання для гэтых файлаў. Дрэнныя назвы для старонкі і малюнка. Выправіць недахопы апісаныя ніжэй і АНАЛАГІЧНЫЯ.

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +== Шаблоны проектов
Любая старонка пачынаецца з header 1 узроўню 
```suggestion
= Шаблоны проектов
```

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +java-приложение.
Зрабіць адзін радок, а не некалькі

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +----
Дадаць пусты радок паміш кодам і звычайным параграфам

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +----
```suggestion
следющую команду:

[source, shell script]
----
```

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +image::assets/img/maven/MavenStructureProject.png[width=256,alt="maven structure project"]
дададць `imagedir` для старонкі, а не для кожнага малюнку

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +Наш *pom.xml* файл будет выглядеть следующим образом:
```suggestion
Наш `pom.xml` файл будет выглядеть следующим образом:
```

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +----
```suggestion
[source, xml]
----
```

2021-05-12 12:12 UTC, rakovets commented on asciidoc/Maven.adoc
> +</project>
Гэта немагчыма чытаць, зрабіць так, каб стала магчыма.

2021-05-12 17:39 UTC, rakovets requested changes
Fix it

2021-05-12 17:39 UTC, rakovets commented on maven/project-templates.adoc
> +[sourse,shell script]
Гэта звычайны вывад, а некаманда ці мова праграмавання
```suggestion
```

2021-05-12 17:39 UTC, rakovets commented on maven/project-templates.adoc
> +[sourse,shell script]
```suggestion
```

2021-05-12 17:39 UTC, rakovets commented on maven/project-templates.adoc
> +<modelVersion>4.0.0</modelVersion>
```suggestion
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
```

2021-05-12 17:39 UTC, rakovets commented on maven/project-templates.adoc
> +image::project-structure-example.png[project structure]
```suggestion
image::project-structure-example.png[Project structure]
```

2021-05-13 20:43 UTC, ttokamo commented on maven/project-templates.adoc
> +И вводим `Y`, после чего нажимаем _Enter_.
```suggestion
Вводим `Y`, после чего нажимаем _Enter_.
```

2021-05-13 20:48 UTC, ttokamo commented on maven/project-templates.adoc
> +Переходим в нужную нам директорию и выполняем в терминале следющую команду:
```suggestion
Переходим в нужную директорию и выполняем в терминале следующую команду:
```
Как правило, в документациях лучше избегать местоимений

2021-05-13 20:49 UTC, ttokamo commented on maven/project-templates.adoc
> +В результате мы получим следующее:
```suggestion
В результате получим следующее:
```

2021-05-13 20:49 UTC, ttokamo commented on maven/project-templates.adoc
> +Выбираем число `7` и нужную нам версию. После этого указываем наши параметры.
```suggestion
Выбираем число `7` и нужную версию. После этого указываем параметры.
```

2021-05-13 20:49 UTC, ttokamo commented on maven/project-templates.adoc
> +В итоге мы получим следующий результат:
```suggestion
В итоге получим следующий результат:
```

2021-05-13 20:49 UTC, ttokamo commented on maven/project-templates.adoc
> +В результате мы получим следующую структуру проекта:
```suggestion
В результате получим следующую структуру проекта:
```

2021-05-13 20:50 UTC, ttokamo commented on maven/project-templates.adoc
> +Наш `pom.xml` файл будет выглядеть следующим образом:
```suggestion
`pom.xml` файл будет выглядеть следующим образом:
```

2021-05-13 20:53 UTC, ttokamo requested changes
Местоимения не нужны в документациях такого типа

2021-05-14 07:34 UTC, ttokamo submitted a review, later dismissed

2021-05-19 05:56 UTC, davydovbv approved these changes

2021-05-22 05:24 UTC, rakovets submitted a review, later dismissed
Approved

2021-05-23 05:41 UTC, rakovets approved these changes
Approved

2021-05-23 12:13 UTC, EvgeniErmakov approved these changes

2021-05-24 14:39 UTC, davydovbv approved these changes

2021-05-24 15:56 UTC, merged