feature-davydov / it-academy.by / M-JC1-69-21 / Bozhen Davydov / Done task: Maven Plugin Guide
rakovets/workshop-asciidoc pull request #15
Opened 2021-05-12 09:03 UTC by davydovbv

2021-05-12 10:43 UTC, Deimos1311 requested changes

2021-05-12 10:43 UTC, Deimos1311 commented on maven/maven-plugins-guid.adoc
> +Плагины Maven используются для:
```suggestion
Плагины *Maven* используются для:
```

2021-05-12 10:43 UTC, Deimos1311 commented on maven/maven-plugins-guid.adoc
> +В результате выполнения команды, получим, примерно, следующий результат:
добавить пустую строчку между кодом и текстом

2021-05-12 10:43 UTC, Deimos1311 commented on maven/maven-plugins-guid.adoc
> +После этого выполним в терминале следующую команду:
добавить пустую строчку между кодом и текстом

2021-05-12 10:43 UTC, Deimos1311 commented on maven/maven-plugins-guid.adoc
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
```suggestion
Для понимания того, как это работает на практике, рассмотрим следующий пример :

----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
```

2021-05-12 11:28 UTC, EvgeniErmakov approved these changes

2021-05-12 11:30 UTC, Deimos1311 approved these changes

2021-05-12 12:00 UTC, rakovets requested changes
Табе патрэбна выправіць недахопы прыведзеныя ніжэй

2021-05-12 17:44 UTC, rakovets requested changes
Fix it

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +Очищает цель после сборки. Удаляет директорию target.
```suggestion
Очищает цель после сборки. Удаляет директорию `target`.
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +Запускает тесты JUnit. Создаёт отчёты о тестировании.
```suggestion
Запускает тесты *JUnit*. Создаёт отчёты о тестировании.
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +Собирает JAR файл текущего проекта.
```suggestion
Собирает *JAR* файл текущего проекта.
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +Собирает WAR файл текущего проекта.
```suggestion
Собирает *WAR* файл текущего проекта.
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +Запускает набор задач ant из любой указанной фазы.
```suggestion
Запускает набор задач *ant* из любой указанной фазы.
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +Генерирует Javadoc проекта.
```suggestion
Генерирует *Javadoc* проекта.
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +<modelVersion>4.0.0</modelVersion>
```suggestion
    <modelVersion>4.0.0</modelVersion>
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```suggestion
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

2021-05-12 17:44 UTC, rakovets commented on maven/maven-plugins-guid.adoc
> +[source, shell script]
Remove it

2021-05-13 02:25 UTC, rakovets requested changes
Табе патрэбна выправіць УСЕ недахопы, а толькі потым рабіць паўторны PR

2021-05-13 08:29 UTC, EvgeniErmakov submitted a review, later dismissed

2021-05-13 10:57 UTC, EvgeniErmakov submitted a review, later dismissed

2021-05-19 04:40 UTC, ttokamo approved these changes

2021-05-22 05:25 UTC, rakovets approved these changes
Approved

2021-05-22 10:18 UTC, EvgeniErmakov approved these changes

2021-05-22 10:18 UTC, merged