feature-alekseev / it-academy.by / M-JC1-69-21 / Aleksei Alekseev / Done task "AsciiDoc"
rakovets/workshop-asciidoc pull request #18
Opened 2021-05-12 22:00 UTC by ttokamo

2021-05-13 08:28 UTC, EvgeniErmakov approved these changes

2021-05-13 17:46 UTC, rakovets requested changes
Неабходна выправіць наступныя памылкі.

2021-05-13 17:46 UTC, rakovets commented on maven/introducing.adoc
> +=== Основные понятия
```suggestion
== Основные понятия
```

2021-05-13 17:46 UTC, rakovets commented on maven/introducing.adoc
> +*Maven – это средство для управления и сборки проектов. Он позволяет разработчикам полностью управлять жизненным циклом проекта. Благодаря этому, команда может автоматизировать процессы, связанные со
```suggestion
*Maven* – это средство для управления и сборки проектов. Он позволяет разработчикам полностью управлять *жизненным циклом* проекта. Благодаря этому, команда может автоматизировать процессы, связанные со сборкой, тестированием, упаковкой проекта
```

2021-05-13 17:46 UTC, rakovets commented on maven/introducing.adoc
> +=== Основная цель
```suggestion
== Основная цель
```

2021-05-13 17:46 UTC, rakovets commented on maven/introducing.adoc
> +Структура и содержание проекта *Maven* указывается в специальном xml-файле, который называется *Project Object Model (POM)*, который является базовым модулем всей системы.
```suggestion
Структура и содержание проекта *Maven* указывается в специальном xml-файле, который называется *Project Object Model* (*POM*), который является базовым модулем всей системы.
```

2021-05-13 17:46 UTC, rakovets commented on maven/introducing.adoc
> +Исходный код, /src/main/java
```suggestion
*Исходный код*, `/src/main/java`
```

2021-05-14 07:40 UTC, Deimos1311 submitted a review, later dismissed

2021-05-19 05:06 UTC, davydovbv submitted a review, later dismissed

2021-05-22 05:28 UTC, rakovets requested changes
Патрэбна выправіць наступныя недахопы.

2021-05-22 05:28 UTC, rakovets commented on maven/introducing.adoc
> +|=========================================
```suggestion
|===
```

2021-05-22 05:28 UTC, rakovets commented on maven/introducing.adoc
> +|=========================================
```suggestion
|===
```

2021-05-22 05:28 UTC, rakovets commented on maven/introducing.adoc
> +Для того, чтобы построить проект, *Maven* предоставляет настройки для управления жизненным циклом проекта и его зависимостями. Большая часть его задач поддерживается плагинами Maven.
```suggestion
Для того, чтобы построить проект, *Maven* предоставляет настройки для управления жизненным циклом проекта и его зависимостями. Большая часть его задач поддерживается *плагинами Maven*.
```

2021-05-26 15:04 UTC, rakovets submitted a review, later dismissed
Approved

2021-05-26 17:28 UTC, rakovets approved these changes
Approved

2021-05-27 05:54 UTC, Deimos1311 approved these changes

2021-05-27 06:34 UTC, EvgeniErmakov approved these changes

2021-05-27 13:58 UTC, vitovtbel approved these changes

2021-05-27 17:12 UTC, merged