feature-alekseev / it-academy.by / M-JC1-69-21 / Aleksandr Lukyanovich / Done task "AsciiDoc"
rakovets/workshop-asciidoc pull request #19
Opened 2021-05-14 22:11 UTC by Alex-210778

2021-05-15 18:56 UTC, ttokamo commented on maven/snapshots.adoc
> +� ���� ������, ������� *business-logic* ����� ��������� snapshot ������ ���������� �� ����������� � ���� business-logic:1.0-SNAPSHOT ������� ���������� jar ����.
```suggestion
� ���� ������, ������� *business-logic* ����� ��������� snapshot ������ ���������� �� ����������� � ���� _business-logic:1.0-SNAPSHOT_ ������� ���������� jar ����.
```

2021-05-15 20:11 UTC, ttokamo commented on maven/snapshots.adoc
> +=================================================
Нечитабельно. Сделай правильные переносы строк.

2021-05-15 20:12 UTC, ttokamo commented on maven/snapshots.adoc
> +На этом мы заканчиваем изучение *snapshot*.
```suggestion
```
Это не нужно

2021-05-15 20:13 UTC, ttokamo commented on maven/snapshots.adoc
> +Для того чтобы подтянуть крайний snapshot нам необходимо использовать *-U* в каждой команде.
```suggestion
Для того чтобы подтянуть крайний snapshot необходимо использовать *-U* в каждой команде.
```
Лишнее местоимение

2021-05-15 20:14 UTC, ttokamo commented on maven/snapshots.adoc
> +Например, одна команда работает над бизнес логикой приложения и они используют проект *business-logic* (business-logic.jar.1.0), а другая команда работает на внешним видом приложения и разрабатывает
```suggestion
Например, одна команда работает над бизнес логикой приложения и они используют проект *business-logic* (_business-logic.jar.1.0_), а другая команда работает на внешним видом приложения и разрабатывает проект *app-front-end* (_app-front-end.jar:1.0_).
```

2021-05-15 20:15 UTC, ttokamo commented on maven/snapshots.adoc
> +В случае со *snapshot*, *Maven* автоматически будет подтягивать крайний *snapshot (business-logic:1.0-SNAPSHOT)* каждый раз, когда команда front-end будет выполнять сборку своего проекта.
```suggestion
В случае со *snapshot*, *Maven* автоматически будет подтягивать крайний *snapshot* (_business-logic:1.0-SNAPSHOT_) каждый раз, когда команда front-end будет выполнять сборку своего проекта.
```

2021-05-15 20:16 UTC, ttokamo requested changes
Нужен фикс

2021-05-19 04:35 UTC, ttokamo submitted a review, later dismissed

2021-05-22 05:43 UTC, rakovets requested changes
Патрэбна выправіць наступныя памылкі і дадаць спасылку на сваю старонку ў `index.adoc`

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +----
```suggestion
[source, xml]
----
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +----
[source, xml]
----

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +*mvn clean package -U*
```suggestion
[source, shell script]
----
mvn clean package -U
----
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +Для того чтобы подтянуть крайний snapshot необходимо использовать *-U* в каждой команде.
```suggestion
Для того чтобы подтянуть крайний *snapshot* необходимо использовать `-U` в каждой команде.
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +Например, одна команда работает над бизнес логикой приложения и они используют проект *business-logic* (_business-logic.jar.1.0_), а другая команда работает на внешним видом приложения и разрабатывае
```suggestion
Например, одна команда работает над бизнес логикой приложения и они используют проект *business-logic* (`business-logic.jar.1.0`), а другая команда работает на внешним видом приложения и разрабатывает проект *app-front-end* (`app-front-end.jar:1.0`).
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +* команда *front-end* должна обновлять свой файл _pom.xml_ для того, чтобы иметь текущую версию продукта.
```suggestion
* команда *front-end* должна обновлять свой файл `pom.xml` для того, чтобы иметь текущую версию продукта.
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +В этом случае, команда *business-logic* будет выпускать *snapshot* своего обновления на репозиторий в виде *business-logic:1.0-SNAPSHOT* замещая предыдущий *jar файл*.
```suggestion
В этом случае, команда *business-logic* будет выпускать *snapshot* своего обновления на репозиторий в виде `business-logic:1.0-SNAPSHOT` замещая предыдущий *jar файл*.
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +В случае со *snapshot*, *Maven* автоматически будет подтягивать крайний *snapshot* (_business-logic:1.0-SNAPSHOT_) каждый раз, когда команда front-end будет выполнять сборку своего проекта.
```suggestion
В случае со *snapshot*, *Maven* автоматически будет подтягивать крайний *snapshot* (`business-logic:1.0-SNAPSHOT`) каждый раз, когда команда front-end будет выполнять сборку своего проекта.
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +Вот как это выглядит в _pom.xml_ файле:
```suggestion
Вот как это выглядит в `pom.xml` файле:
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +
```suggestion
.`pom.xml` *для front-end*
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +
```suggestion
.`pom.xml` для *business-logic*
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +    </project>
```suggestion
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>business-logic</groupId>
    <artifactId>business-logic</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>maven-tutorial</name>
    <url>http://maven.apache.org</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
```

2021-05-22 05:43 UTC, rakovets commented on maven/snapshots.adoc
> +</project>
```suggestion
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>front-end</groupId>
    <artifactId>front-end</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <name>maventutorial</name>
    <url>http://maven.apache.org</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
        <groupId>data-service</groupId>
            <artifactId>business-logic</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

2021-05-24 04:27 UTC, rakovets requested changes
Патрэбна выправіць прыведзеныя ніжэй недахобы.

2021-05-24 04:27 UTC, rakovets commented on maven/snapshots.adoc
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
```suggestion
[source, xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0"
```

2021-05-24 04:27 UTC, rakovets commented on maven/snapshots.adoc
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
```suggestion
</project>
----

.`pom.xml` для *business-logic*
[source, xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0"
```

2021-05-24 04:27 UTC, rakovets commented on maven/snapshots.adoc
> +[source, xml]
```suggestion
.`pom.xml` для *front-end*
[source, xml]
```

2021-05-25 12:27 UTC, rakovets approved these changes
Approved

2021-05-27 05:54 UTC, Deimos1311 approved these changes

2021-05-27 06:34 UTC, EvgeniErmakov approved these changes

2021-05-27 06:57 UTC, vitovtbel approved these changes

2021-05-27 13:52 UTC, ttokamo approved these changes

2021-05-27 17:14 UTC, merged