Feature busheyko
rakovets/workshop-asciidoc pull request #20
Opened 2021-05-28 09:49 UTC by busheyko

2021-05-28 11:25 UTC, Deimos1311 requested changes
Need to fix

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +В этом случае, сначала будет выполнена фаза clean, после этого будет выполнена задача dependency: copy-dependencies. После чего будет выполнена фаза package.
```suggestion
В этом случае, сначала будет выполнена фаза *clean*, после этого будет выполнена задача *dependency: copy-dependencies*. После чего будет выполнена фаза *package*.
```

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +Когда вы выполняете команду
Нельзя использовать местоимения, необходимо корректно редактировать текст

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +Задача clean Maven  (clean:clean) привязывается к фазе clean в жизненном цикле сборки. Эта задача удаляет ввод сборки путём удаления директории сборки. Таким образом, когда выполняется команда *mvn c
```suggestion
Задача *clean* *Maven*  (*clean:clean*) привязывается к фазе *clean* в *жизненном цикле* сборки. Эта задача удаляет ввод сборки путём удаления директории сборки. Таким образом, когда выполняется команда *mvn clean*, *Maven* удаляет директорию сборки.
```

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +Рассмотрим пример, в котором мы привяжем задачу maven-antrun-plugin:run к фазам pre-clean, clean и post-clean.
Нельзя использовать местоимения, необходимо корректно редактировать текст

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +Плагин Maven – Site – используется для создания докладов, документации, развёртывания и т.д.
```suggestion
*Плагин Maven* – *Site* – используется для создания докладов, документации, развёртывания и т.д.
```

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +----
Добавить пустые строки. Удалить местоимения

2021-05-28 11:25 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +В следующем уроке мы изучим профиль сборки.
```suggestion
```

2021-05-28 12:03 UTC, Deimos1311 requested changes
Need to fix

2021-05-28 12:03 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +Теперь выполним команду Maven:
```suggestion
Теперь выполним команду *Maven*:
```

2021-05-28 12:03 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +В следующем примере, привязываем задачу maven-antrun-plugin:run к нескольким фазам жизненного цикла сборки. Это также позволяет нам вызывать текстовые сообщения, отображая фазу жизненного цикла.
Добавить выделение

2021-05-28 12:03 UTC, Deimos1311 commented on maven/build-life-cycle.adoc
> +Рассмотрим пример, в котором привяжем задачу maven-antrun-plugin:run к фазам *pre-clean*, *clean* и *post-clean*.
```suggestion
Рассмотрим пример, в котором привяжем задачу *maven-antrun-plugin:run* к фазам *pre-clean*, *clean* и *post-clean*.
```

2021-05-28 12:16 UTC, Deimos1311 submitted a review, later dismissed

2021-05-28 18:42 UTC, davydovbv requested changes
mark this as a code part.

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +В следующем примере, привязываем задачу *maven-antrun-plugin:run* к нескольким фазам жизненного цикла сборки. Это также позволяет нам вызывать текстовые сообщения, отображая фазу жизненного цикла.
```suggestion
В следующем примере, привязываем задачу `maven-antrun-plugin:run` к нескольким фазам жизненного цикла сборки. Это также позволяет нам вызывать текстовые сообщения, отображая фазу жизненного цикла.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +Например, рассмотрим команду ниже. Аргументы *clean* и *package* являются фазами сборки до тех пор, пока *dependency: copy-dependencies* является задачей.
```suggestion
Например, рассмотрим команду ниже. Аргументы `clean` и `package` являются фазами сборки до тех пор, пока *dependency: copy-dependencies* является задачей.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +Каждая из этих фаз имеет фазы *pre* и *post*. Они могут быть использованы для регистрации задач, которые должны быть запущены перед и после указанной фазы.
```suggestion
Каждая из этих фаз имеет фазы `pre` и `post`. Они могут быть использованы для регистрации задач, которые должны быть запущены перед и после указанной фазы.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +Например, рассмотрим команду ниже. Аргументы *clean* и *package* являются фазами сборки до тех пор, пока *dependency: copy-dependencies* является задачей.
```suggestion
Например, рассмотрим команду ниже. Аргументы `clean` и `package` являются фазами сборки до тех пор, пока *dependency: copy-dependencies* является задачей.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +В этом случае, сначала будет выполнена фаза *clean*, после этого будет выполнена задача *dependency: copy-dependencies*. После чего будет выполнена фаза *package*.
```suggestion
В этом случае, сначала будет выполнена фаза `clean`, после этого будет выполнена задача `dependency: copy-dependencies`. После чего будет выполнена фаза `package`.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +Задача *clean Maven*  (*сlean:clean*) привязывается к фазе *clean* в жизненном цикле сборки. Эта задача удаляет ввод сборки путём удаления директории сборки. Таким образом, когда выполняется команда
```suggestion
Задача *clean Maven*  (*сlean:clean*) привязывается к фазе `clean` в жизненном цикле сборки. Эта задача удаляет ввод сборки путём удаления директории сборки. Таким образом, когда выполняется команда `mvn clean`, *Maven* удаляет директорию сборки.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +Рассмотрим пример, в котором привяжем задачу *maven-antrun-plugin:run* к фазам *pre-clean*, *clean* и *post-clean*.
```suggestion
Рассмотрим пример, в котором привяжем задачу `maven-antrun-plugin:run` к фазам `pre-clean`, `clean` и `post-clean`.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +Можем выполнить такие же действия для фаз *pre-clean* и *clean*.
```suggestion
Можем выполнить такие же действия для фаз `pre-clean` и `clean`.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +* Когда выполняем команду *Maven*, например *install*, то будут выполнены фазы до *install* и фаза *install*.
```suggestion
* Когда выполняем команду *Maven*, например `install`, то будут выполнены фазы до `install` и фаза `install`.
```

2021-05-28 18:42 UTC, davydovbv commented on maven/build-life-cycle.adoc
> +В примере ниже прикрепляем задачу *maven-antrun-plugin:run* ко всем фазам *жизненного цикла* *Site*. Это позволяет вызывать текстовые сообщения для отображения фаз жизненного цикла.
```suggestion
В примере ниже прикрепляем задачу `maven-antrun-plugin:run` ко всем фазам *жизненного цикла* *Site*. Это позволяет вызывать текстовые сообщения для отображения фаз жизненного цикла.
```

2021-05-28 19:01 UTC, davydovbv approved these changes

2021-05-28 19:03 UTC, EvgeniErmakov approved these changes

2021-05-28 19:06 UTC, Deimos1311 submitted a review, later dismissed

2021-05-30 03:52 UTC, rakovets requested changes
Патрэбна выправіць усе недахопы і адправіць на рэв'ю толькі мне. Здымаць мінулыя пацверджанні, не буду.

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +*install*,	Установка,	"В этой фазе происходит установка пакета в локальный/удалённый репозиторий *Maven*."
```suggestion
Фаза, Действия, Описание
*prepare-resources*, Копирование ресурсов, "В этой фазе происходит копирование ресурсов, которое, также, может быть настроено."
*compile*, Компиляция, "В этой фазе происходит компиляция исходного кода."
*package*, Создание пакета, "В этой фазе, в зависимости от настроек создаётся архив *JAR/WAR*. Тип архива указывается в `pom.xml` файле."
*install*, Установка, "В этой фазе происходит установка пакета в локальный/удалённый репозиторий *Maven*."
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +|========================================
```suggestion
|===
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +|========================================
```suggestion
|===
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +Задача (*goal*) – это специальная задача, которая относится к сборке проекта и его управлению. Она может привязываться как к нескольким фазам, так и ни к одной. Задача, которая не привязана ни к одно
```suggestion
*Задача* (*goal*) – это специальная задача, которая относится к сборке проекта и его управлению. Она может привязываться как к нескольким фазам, так и ни к одной. *Задача*, которая не привязана ни к одной фазе, может быть запущена вне фаз сборки с помощью прямого вызова.
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +Например, рассмотрим команду ниже. Аргументы `clean` и `package` являются фазами сборки до тех пор, пока *dependency: copy-dependencies* является задачей.
```suggestion
Например, рассмотрим команду ниже. Аргументы `clean` и `package` являются фазами сборки до тех пор, пока `dependency:copy-dependencies` является задачей.
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +В этом случае, сначала будет выполнена фаза `clean`, после этого будет выполнена задача `dependency: copy-dependencies`. После чего будет выполнена фаза `package`.
```suggestion
В этом случае, сначала будет выполнена фаза `clean`, после этого будет выполнена задача `dependency:copy-dependencies`. После чего будет выполнена фаза `package`.
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +|========================================
```suggestion
|===
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +|========================================
```suggestion
|===
```

2021-05-30 03:52 UTC, rakovets commented on maven/build-life-cycle.adoc
> +*deploy*,	"Копирует финальный пакет (архив) в удалённый репозиторий для, того, чтобы сделать его доступным другим разработчикам и проектам."
Замяніць tab на whitespace

2021-05-30 16:02 UTC, EvgeniErmakov approved these changes

2021-05-30 18:15 UTC, Deimos1311 approved these changes

2021-05-30 21:29 UTC, davydovbv approved these changes

2021-05-31 02:03 UTC, rakovets approved these changes
Approved

2021-05-31 07:53 UTC, merged