hw3/Feature Skopinau
rakovets/workshop-asciidoc pull request #27
Opened 2021-12-10 12:38 UTC by Dyskop

2021-12-12 15:32 UTC, AleksandrTolkach submitted a review, later dismissed
Необходимо удалить "Wiki for Example".
Возможно стоит удалить неработающие ссылки.

2021-12-12 16:24 UTC, evzhigalko requested changes
1. исправить однотипную ошибку, элементы коды (название типов, методов, классов, интерфейсов и т.д.) стоит оформлять через \`Name\`
2. сделать ссылки рабочими

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*Коллекция Java, которая хранит последовательность элементов и в которой допускается хранение одинаковых элементов называется List*. Получить доступ к любому элементу List можно по индексу.
оставить выделение жирным шрифтом только List

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*List* связывается (mapped) с помощью элемента *<list>* и инициализируется с помощью *java.util.ArrayList*.
1. сделать с большой буквы <List> выделить как  элемент кода с помощью \`<List>\`,
2. тоже самое вместо выделения жирным \`java.util.ArrayList\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +Исходный код проекта можно скачать по *_https://xxx[ЭТОЙ ССЫЛКЕ]_*.
не рабочая ссылка, стоит скопировать верный адрес

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*Developer.java*
оформить как элемент кода \`Developer.java\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*Project.java*
оформить как элемент кода \`Project.java\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*hibernate.cfg.xml*
Здесь бы я тоже выделил через \`hibernate.cfg.xml\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*Developer.hbm.xml*
Здесь бы я тоже выделил через \`Developer.hbm.xml\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*DeveloperRunner.java*
через  \`DeveloperRunner.java\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +*Коллекция Java, которая хранит элементы без какой-либо последовательности и позволяет хранение одинаковых элементов, называется Bag.*
я бы оставил жирное выделение только у Bag, т.е. \*Bag\*

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +Исходный код проекта можно скачать по https://xxx[*_ЭТОЙ ССЫЛКЕ_*].
ссылка не рабочая

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +*Developer.java*
\`Developer.java\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +*Project.java*
\`Project.java\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +*hibernate.cfg.xml*
\`hibernate.cfg.xml\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +*Deveoper.hbm.xml*
\`Developer.hbm.xml\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +*DeveloperRunner.java*
\`DeveloperRunner.java\`

2021-12-12 16:24 UTC, evzhigalko commented on hibernate_manual/сollection_mapping.adoc
> +В этой статье рассмотрен пример связывания с использованием Collection.
я бы указал \`Collection\`

2021-12-12 17:54 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*Коллекция Java, которая хранит последовательность элементов и в которой допускается хранение одинаковых элементов называется List*. Получить доступ к любому элементу List можно по индексу.
done

2021-12-12 18:01 UTC, AleksandrTolkach approved these changes, later dismissed

2021-12-12 18:04 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*List* связывается (mapped) с помощью элемента *<list>* и инициализируется с помощью *java.util.ArrayList*.
Как элемент кода повыделял, с написанием с большой буквы не согласен, я не вижу тут имени собственного чего-либо

2021-12-12 18:05 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +Исходный код проекта можно скачать по *_https://xxx[ЭТОЙ ССЫЛКЕ]_*.
По этой ссылке на оригинальном сайте скачивался файл, я не знаю, как сделать также, поэтому просто удаляю этот текст

2021-12-12 18:12 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*Developer.java*
done

2021-12-12 18:13 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*Project.java*
done

2021-12-12 18:13 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*hibernate.cfg.xml*
done

2021-12-12 18:13 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*Developer.hbm.xml*
done

2021-12-12 18:13 UTC, Dyskop commented on hibernate_manual/list_mapping.adoc
> +*DeveloperRunner.java*
done

2021-12-12 18:14 UTC, evzhigalko commented on hibernate_manual/list_mapping.adoc
> +*List* связывается (mapped) с помощью элемента *<list>* и инициализируется с помощью *java.util.ArrayList*.
согласен, здесь все-таки имеется ввиду часть xml кода

2021-12-12 18:22 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +*Коллекция Java, которая хранит элементы без какой-либо последовательности и позволяет хранение одинаковых элементов, называется Bag.*
done

2021-12-12 18:23 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +Исходный код проекта можно скачать по https://xxx[*_ЭТОЙ ССЫЛКЕ_*].
ссылка удалена

2021-12-12 18:23 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +*Developer.java*
done

2021-12-12 18:23 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +*Project.java*
done

2021-12-12 18:23 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +*hibernate.cfg.xml*
done

2021-12-12 18:23 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +*Deveoper.hbm.xml*
done

2021-12-12 18:23 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +*DeveloperRunner.java*
done

2021-12-12 18:24 UTC, Dyskop commented on hibernate_manual/сollection_mapping.adoc
> +В этой статье рассмотрен пример связывания с использованием Collection.
done

2021-12-12 20:56 UTC, skarmyzov approved these changes

2021-12-12 20:58 UTC, skarmyzov submitted a review, later dismissed

2021-12-13 07:24 UTC, evzhigalko approved these changes, later dismissed

2021-12-13 10:27 UTC, alexkoval6030 commented on hibernate_manual/list_mapping.adoc
> +Исходный код проекта можно скачать по *_https://xxx[ЭТОЙ ССЫЛКЕ]_*.
Правой клавишей мыши по ссылке и копировать адрес ссылки, вставить в своём документе

2021-12-13 10:55 UTC, AleksandrTolkach approved these changes, later dismissed

2021-12-13 11:00 UTC, IlyaKolbasov approved these changes, later dismissed
Ok

2021-12-13 11:41 UTC, skarmyzov approved these changes

2021-12-13 11:41 UTC, AleksandrTolkach approved these changes

2021-12-13 11:43 UTC, IlyaKolbasov approved these changes

2021-12-13 11:45 UTC, merged