Feature karmyzov
rakovets/workshop-asciidoc pull request #28
Opened 2021-12-11 17:56 UTC by skarmyzov

Please reviewiev my mapping-files.adoc and persistent-classes.adoc

2021-12-12 17:57 UTC, AleksandrTolkach reviewed
Нужно удалить файлы с примерами. 
В index.adoc добавить ссылки на свои страницы.

2021-12-12 19:02 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +* *<hibernate-mapping>* +
я думаю, что <hibernate-mapping> нужно выделять как код с помощью `<hibernate-mapping>`, так как это тэг

2021-12-12 19:03 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +* *<class>* +
`<class>`

2021-12-12 19:04 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +Тег <class> используется для того, чтобы указать связь между POJO – классов и таблицей в БД. Имя класса указывается с помощью свойства *name*, имя таблицы в БД – с помощью свойства *table*.
предлагаю выделить с помощью ``

2021-12-12 19:04 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +* *<meta>* +
предлагаю выделить с помощью ``

2021-12-12 19:04 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +* *<id>* +
предлагаю выделить с помощью ``

2021-12-12 19:08 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +Тег <id > связывает уникальный идентификатор ID в POJO – классе и первичный ключ (primary key) в таблице БД. Свойство *name* соединяет поле класса со свойством *column*, которое указывает нам колонку
предлагаю выделить с помощью ``

2021-12-12 19:09 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +* *<property>* +
предлагаю выделить с помощью ``

2021-12-12 19:09 UTC, Dyskop commented on karmyzov/mapping-files.adoc
> +* *<generator>* +
предлагаю выделить с помощью ``

2021-12-12 19:18 UTC, Dyskop requested changes
Пока не делаю approve, так как не выполнены условия 7 (Удалить все файлы и ссылки связанные с примером) и 5 (Добавить ссылку на файл в index.adoc). Если сделаешь мне review, то можешь увидеть пример index.adoc.

2021-12-12 20:37 UTC, Dyskop approved these changes, later dismissed
Подправь файл index, а файл readme, я думаю не стоило удалять, я оставил, думаю, он не имеет отношения к примеру

2021-12-12 20:37 UTC, Dyskop commented on index.adoc
>  Wiki for 'Example'.
Эту строку лучше тоже удалить и вверху вместо Theme указать название своей темы

2021-12-12 20:37 UTC, skarmyzov commented on index.adoc
>  Wiki for 'Example'.
Ok / спасибо как раз сижу ща разбираюсь что это

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +* *<class>* +
ok

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +Тег <class> используется для того, чтобы указать связь между POJO – классов и таблицей в БД. Имя класса указывается с помощью свойства *name*, имя таблицы в БД – с помощью свойства *table*.
ok

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +* *<meta>* +
ok

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +* *<id>* +
ok

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +Тег <id > связывает уникальный идентификатор ID в POJO – классе и первичный ключ (primary key) в таблице БД. Свойство *name* соединяет поле класса со свойством *column*, которое указывает нам колонку
ok

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +* *<property>* +
ok

2021-12-12 20:47 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +* *<generator>* +
ok

2021-12-12 21:25 UTC, AleksandrTolkach submitted a review, later dismissed
Ок

2021-12-12 21:30 UTC, Dyskop submitted a review, later dismissed

2021-12-13 08:13 UTC, evzhigalko reviewed
устрани небольшие ошибки, см. комментарии

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +Теперь создадим таблицу в БД +
задание: заменить текст ссылающий на последующую таблицу/изображение/код/команду на заголовок к этому блоку (Block title).
я бы сделал так:  \.Теперь создадим таблицу в БД + `HIBERNATE_DEVELOPERS`:

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +Тег <class> используется для того, чтобы указать связь между POJO – классов и таблицей в БД. Имя класса указывается с помощью свойства `name`, имя таблицы в БД – с помощью свойства `table`.
добавь \`\` к тегу class

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +Тег <id > связывает уникальный идентификатор ID в POJO – классе и первичный ключ (primary key) в таблице БД. Свойство `name` соединяет поле класса со свойством `column`, которое указывает нам колонку
добавь `` к тегу id

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +А в этой статье описаны основы применения соединяющих файлов `(mapping files)`.
здесь не нужно как элемент кода, я бы сделал просто \*mapping files\*

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/persistent-classes.adoc
> +В этой статье рассматривались основные понятия сохраняемых классов `(persistent classes)`.
здесь я бы просто жирным выделил бы

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/persistent-classes.adoc
> +Пример `Developer.java`:
заменить текст ссылающий на последующую таблицу/изображение/код/команду на заголовок к этому блоку (Block title). 
я бы сделал: \.Пример `Developer.java`

2021-12-13 08:13 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +*POJO – класс `Developer.java`*
заменить текст ссылающий на последующую таблицу/изображение/код/команду на заголовок к этому блоку (Block title).
здесь жирное можно убрать и сделать: \.POJO – класс \`Developer.java\`

2021-12-13 09:46 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +Теперь создадим таблицу в БД +
Тут не понял , у меня ж вроде так и сделано  Теперь создадим таблицу в БД +
`HIBERNATE_DEVELOPERS`:

2021-12-13 09:46 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +*POJO – класс `Developer.java`*
ok

2021-12-13 09:46 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +Тег <class> используется для того, чтобы указать связь между POJO – классов и таблицей в БД. Имя класса указывается с помощью свойства `name`, имя таблицы в БД – с помощью свойства `table`.
ok

2021-12-13 09:46 UTC, skarmyzov commented on karmyzov/mapping-files.adoc
> +А в этой статье описаны основы применения соединяющих файлов `(mapping files)`.
ok

2021-12-13 09:46 UTC, skarmyzov commented on karmyzov/persistent-classes.adoc
> +Пример `Developer.java`:
ок

2021-12-13 09:46 UTC, skarmyzov commented on karmyzov/persistent-classes.adoc
> +В этой статье рассматривались основные понятия сохраняемых классов `(persistent classes)`.
ok

2021-12-13 10:07 UTC, AleksandrTolkach commented on karmyzov/mapping-files.adoc
> +Теперь создадим таблицу в БД +
он имеет ввиду поставить точку перед "Теперь", таким образом ты получишь необязательный заголовок

2021-12-13 10:07 UTC, AleksandrTolkach approved these changes
пушка

2021-12-13 10:12 UTC, skarmyzov commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
pre
	{mso-style-priority:99;
	mso-style-link:"HTML Preformatted Char";
	margin:0cm;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTMLPreformattedChar
	{mso-style-name:"HTML Preformatted Char";
	mso-style-priority:99;
	mso-style-link:"HTML Preformatted";
	font-family:"Courier New";}
MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:2.0cm 42.5pt 2.0cm 3.0cm;}
div.WordSection1
	{page:WordSection1;}
-->АА  Sent from Mail for Windows From: AleksandrTolkachSent: 13 декабря 2021 г. 13:07To: rakovets/workshop-asciidocCc: Sergrei; AuthorSubject: Re: [rakovets/workshop-asciidoc] Feature karmyzov (PR ***@***.*** commented on this pull request.In karmyzov/mapping-files.adoc:> +    /** +     * toString method (optional) +     */ +    @Override +    public String toString() { +        return "Developer{" + +                "id=" + id + +                ", firstName='" + firstName + '\'' + +                ", lastName='" + lastName + '\'' + +                ", specialty='" + specialty + '\'' + +                ", experience=" + experience + +                '}'; +    } +} +---- +Теперь создадим таблицу в БД + он имеет ввиду поставить точку перед "Теперь", таким образом ты получишь необязательный заголовок—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.   
	
      
		Без вирусов. www.avast.ru

2021-12-13 10:42 UTC, evzhigalko approved these changes
остались мелкие недочеты, но это скорее невнимательность,
approve!

2021-12-13 10:42 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +Теперь создадим таблицу в БД +
не исправлено, на будущее будь внимательнее)

2021-12-13 10:42 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +А в этой статье описаны основы применения соединяющих файлов *(mapping files)*
без скобок сделать жирное выделение

2021-12-13 10:42 UTC, evzhigalko commented on karmyzov/mapping-files.adoc
> +Этот тег внутри тега <id> используется для того, что генерировать первичные ключи автоматически. Если указать это свойство `native`, как в примере, приведённом выше, то Hibernate сам выберет алгоритм
тег не оформлен как элемент кода

2021-12-13 10:49 UTC, ddshcharbunou approved these changes
came to the ready, all is done

2021-12-13 11:24 UTC, merged