Feature tolkach
rakovets/workshop-asciidoc pull request #30
Opened 2021-12-12 16:16 UTC by AleksandrTolkach

Done task asciidoctor. 
Please check.

2021-12-12 16:41 UTC, evzhigalko requested changes
1. Нужно поменять названия файлов с page1 и page2 на названия статей 
остальное все ок, мелкие недочеты , возможно субъективные

2021-12-12 16:41 UTC, evzhigalko commented on dir/page1.adoc
> +`Set` связывается (mapped) с помощью элемента <set> и инициализируется с помощью `java.util.HashSet`.
Исправить на заглавную букву и добавить \`<Set>\`

2021-12-12 16:41 UTC, evzhigalko commented on dir/page1.adoc
> +create table HIBERNATE_PROJECTS (
стоит сделать CREATE TABLE с заглавных букв

2021-12-12 16:41 UTC, evzhigalko commented on dir/page1.adoc
> +.Developer.java
я бы здесь тоже через \`\`

2021-12-12 16:41 UTC, evzhigalko commented on dir/page1.adoc
> +.Project.java
аналогично, думаю лучше добавить  \.\`Project.java\`

2021-12-12 16:41 UTC, evzhigalko commented on dir/page1.adoc
> +.hibernate.cfg.xml
я сделал бы \`.hibernate.cfg.xml\`

2021-12-12 16:41 UTC, evzhigalko commented on dir/page1.adoc
> +.DeveloperRunner.java
аналогично

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +`SortedSet` связывается (mapped) с помощью элемента <set> в таблице связей и инициализируется с помощью `java.util.TreeSet`.
сделать Set с большой буквы и добавить  \`\`

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +.Developer.java
аналогично

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +.Project.java
аналогично

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +.ProjectsComparator.java
аналогично

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +.hibernate.cfg.xml
аналогично

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +.Developer.hbm.xml
аналогично я бы сделал через \`\`

2021-12-12 16:41 UTC, evzhigalko commented on dir/page2.adoc
> +.DeveloperRunner.java
аналогично я бы сделал через ``

2021-12-12 17:09 UTC, Dyskop commented on index.adoc
> +include::dir/page2.adoc[leveloffset=1]
Будет лучше сделать, чтобы вторая ссылка начиналась с новой строки

2021-12-12 17:14 UTC, Dyskop commented on README.adoc
> -    ----
Как по мне, файл readme не стоит удалять, он не относится к примеру, не знаю, на твоё усмотрение

2021-12-12 17:21 UTC, Dyskop commented on dir/page1.adoc
> +
Заменить текст ссылающий на последующую таблицу/изображение/**код**/команду на заголовок к этому блоку.
Я использовал заголовок 2 уровня для всех шагов, думаю, тебе тоже стоит так сделать.

2021-12-12 17:25 UTC, Dyskop commented on dir/page1.adoc
> +Шаг 2. Создаём класс Developer.java
Предлагаю использовать заголовок второго уровня

2021-12-12 17:25 UTC, Dyskop commented on dir/page1.adoc
> +Шаг 3. Создём класс Project.java
Предлагаю использовать заголовок второго уровня

2021-12-12 17:25 UTC, Dyskop commented on dir/page1.adoc
> +Шаг 4. Создаём конфигурационный файл hibernate.cfg.xml
Предлагаю использовать заголовок второго уровня

2021-12-12 17:26 UTC, Dyskop commented on dir/page1.adoc
> +Шаг 5. Создаём конфигурационный файл Developer.hbm.xml
Предлагаю использовать заголовок второго уровня

2021-12-12 17:33 UTC, Dyskop commented on dir/page2.adoc
> +----
Аналогично первой странице, предлагаю использовать заголовки второго уровня для текста, ссылающего на последующий код, в твоём случае это: шаг 1, шаг 2 и т.д.

2021-12-12 17:34 UTC, Dyskop submitted a review, later dismissed

2021-12-12 21:07 UTC, skarmyzov commented
> 1. Нужно поменять названия файлов с page1 и page2 на названия статей
>    остальное все ок, мелкие недочеты , возможно субъективные

Присоединяюсь , назвать по теме set-mapping-example.adoc  и sortedset-mapping-example.adoc

2021-12-12 21:09 UTC, skarmyzov submitted a review, later dismissed

2021-12-12 21:33 UTC, Dyskop submitted a review, later dismissed

2021-12-13 07:33 UTC, evzhigalko reviewed
Не увидел исправления однотипной ошибки, везде где присутствует элемент кода добавлять \`\`, например\`Developer.java\` 
Поправь и будет approve остальное все ок

2021-12-13 07:33 UTC, evzhigalko commented on dir/set-mapping.adoc
> +`Set` связывается (mapped) с помощью элемента <set> и инициализируется с помощью `java.util.HashSet`.
стоит указать как элемент кода через \`<set>\`

2021-12-13 07:33 UTC, evzhigalko commented on dir/set-mapping.adoc
> +.Developer.java
не добавлены \`.Developer.java\`

2021-12-13 07:33 UTC, evzhigalko commented on dir/sorted-set-mapping.adoc
> +`SortedSet` связывается (mapped) с помощью элемента <set> в таблице связей и инициализируется с помощью `java.util.TreeSet`.
добавить \`\<set\>\`

2021-12-13 10:01 UTC, skarmyzov submitted a review, later dismissed

2021-12-13 11:43 UTC, skarmyzov approved these changes, later dismissed

2021-12-13 12:11 UTC, Dyskop commented
Сразу решай merge conflict, так как придётся заново запрашивать approves. В index удали строки
<<<<<<< feature-tolkach
>>>>>>> develop
и по образцу добавь Wiki for 'своя тема' и ниже свои ссылки, например:

Wiki for 'Hibernate manual. Types of connections'.

include::hibernate_manual/list_mapping.adoc[leveloffset=1]

include::hibernate_manual/сollection_mapping.adoc[leveloffset=1]

2021-12-13 12:41 UTC, Dyskop submitted a review, later dismissed

2021-12-13 12:42 UTC, skarmyzov approved these changes, later dismissed

2021-12-13 12:54 UTC, evzhigalko approved these changes, later dismissed

2021-12-13 13:49 UTC, skarmyzov approved these changes

2021-12-13 13:49 UTC, Dyskop approved these changes

2021-12-13 13:56 UTC, ben4a1 approved these changes

2021-12-13 13:56 UTC, merged