Feature kolbasov
rakovets/workshop-asciidoc pull request #31
Opened 2021-12-12 20:07 UTC by IlyaKolbasov

2021-12-13 10:00 UTC, evzhigalko reviewed
исправить небольшие ошибки, однотипные

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Если речь идёт о *Hibernate*, то схематически кэширование можно представить в виде следующего рисунка:
удалить строку

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +image::images-rykovodstvo-po-hibernate-keshirovanie/hibernatecaching.png[]
заменить текст ссылающий на последующую таблицу/изображение/код/команду на заголовок к этому блоку (Block title).
я бы сделал так: 
\.Представление кэширования в случае *Hibernate*
image::images-rykovodstvo-po-hibernate-keshirovanie/hibernatecaching.png[Добавь альтернативный текст картинки]

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +*Кэш первого уровня (First Level Cache)*
здесь лучше сделать подзаголовки 2 уровня

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +*Кэш второго уровня (Second level Cache)*
здесь лучше сделать подзаголовки 2 уровня

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Developer.hbm.xml
я бы сделал как элемент кода \`Developer.hbm.xml\`

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +hibenrate.cfg.xml
я бы сделал как элемент кода `Developer.hbm.xml`, но это субъективно ) здесь на свое усмотрение )

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Два предыдущих фала нам уже знакомы, а теперь нам необходимо создать файл `ehcache.xml`
я бы сделал как элемент кода Developer.hbm.xml, но это субъективно ) здесь на свое усмотрение )

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Нам необходимо выполнить 100,000 записей в таблицу базы данных (далее – БД). Рассмотрим примитивный сопособ:
1. Убрать личное местоимение нам, и по тексту надо убирать такие 
2. лучше сделать в отдельную строку и как название блока (см. последнюю страницу презентации), там  первый пример
\. Рассмотрим примитивный способ

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Шаг 1. Создаём таблицу в нашей БД
я бы шаги расписал как подзаголовки либо 2 уровня, либо через \.Шаг 1. Создаём таблицу в нашей БД

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Developer.java
тут я бы сделал как элемент кода \`Developer.java\`

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +****
я бы сделал через \.Примерно, вот так будет выглядеть наша таблица

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Developer.hbm.xml
я бы сделал через \`\`

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Шаг 4. Создаём класс `DeveloperRunner.java`
описывал уже выше

2021-12-13 10:00 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +DeveloperRunner.java
и здесь

2021-12-13 10:26 UTC, Dyskop commented on index.adoc
> +include::rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc[leveloffset=1]
Следует сделать так, чтобы вторая ссылка начиналась с новой строки

2021-12-13 10:27 UTC, Dyskop commented on index.adoc
> +include::rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc[leveloffset=1]
И вместо Theme указать свою тему

2021-12-13 10:30 UTC, Dyskop commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Если речь идёт о *Hibernate*, то схематически кэширование можно представить в виде следующего рисунка:
заменить текст ссылающий на последующую таблицу/**изображение**/код/команду на заголовок к этому блоку

2021-12-13 10:32 UTC, Dyskop commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +*Кэш первого уровня (First Level Cache)*
+

2021-12-13 10:33 UTC, Dyskop commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +*Кэш второго уровня (Second level Cache)*
подзаголовок

2021-12-13 10:33 UTC, Dyskop commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Developer.hbm.xml
элемент кода ``

2021-12-13 10:33 UTC, Dyskop commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +hibenrate.cfg.xml
элемент кода ``

2021-12-13 10:34 UTC, Dyskop commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Два предыдущих фала нам уже знакомы, а теперь нам необходимо создать файл `ehcache.xml`
элемент кода ``

2021-12-13 10:36 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Нам необходимо выполнить 100,000 записей в таблицу базы данных (далее – БД). Рассмотрим примитивный сопособ:
согласен с Евгением

2021-12-13 10:43 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +написать, примерно, такой кусок кода:
В этом тексте есть личные местоимения, "мы", "нам", нужно их поубирать. Не уверен, насчёт "нам", но "мы" точно.

2021-12-13 10:44 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Шаг 1. Создаём таблицу в нашей БД
Я использовал заголовки 2 уровня для обозначения шагов

2021-12-13 10:45 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Developer.java
выдели как код ``

2021-12-13 10:45 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +hibernate.cfg.xml
выдели как код ``

2021-12-13 10:46 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Шаг 3. Создаём конфигруационные файлы
подзаголовок

2021-12-13 10:46 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Developer.hbm.xml
выдели как код ``

2021-12-13 10:46 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Шаг 4. Создаём класс `DeveloperRunner.java`
аналогично

2021-12-13 10:46 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +DeveloperRunner.java
выдели как код ``

2021-12-13 10:48 UTC, Dyskop commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Если всё было дслеано правильно, то в результате работы программы мыполучим, примерно, следующий результат:
Тоже можно сделать заголовком 2 уровня и немного упростить текст, к примеру "В результате работы программы получится следующий результат:"

2021-12-13 10:49 UTC, dyskop requested changes
Подкорректируй и обновляй запрос на review

2021-12-13 10:52 UTC, evzhigalko commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +написать, примерно, такой кусок кода:
нам тоже надо убрать

2021-12-13 11:24 UTC, AleksandrTolkach commented on index.adoc
Я бы название темы свое написал

2021-12-13 11:26 UTC, AleksandrTolkach commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +Нам необходимо выполнить 100,000 записей в таблицу базы данных (далее – БД). Рассмотрим примитивный сопособ:
+

2021-12-13 11:28 UTC, AleksandrTolkach reviewed
Жду описанных коллегами исправлений. После чего сделаю апрув.

2021-12-13 11:49 UTC, IlyaKolbasov commented on rykovodstvo-po-hibernate-keshirovanie/documenation.adoc
> +Developer.hbm.xml
По-моему в документации это больше похоже на block-title, сделал так же

2021-12-13 11:50 UTC, Dyskop approved these changes, later dismissed

2021-12-13 11:50 UTC, IlyaKolbasov commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +DeveloperRunner.java
BLock- title, аналогично выше.

2021-12-13 11:50 UTC, IlyaKolbasov commented on index.adoc
> +include::rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc[leveloffset=1]
сделал.

2021-12-13 11:51 UTC, IlyaKolbasov commented on rykovodstvo-po-hibernate-obrabotka-paketov/documation.adoc
> +написать, примерно, такой кусок кода:
Убрал

2021-12-13 12:06 UTC, ddshcharbunou requested changes
.Developer.hbm.xml -> `Developer.hbm.xml` (classes, interfaces -> ``)

2021-12-13 12:08 UTC, skarmyzov approved these changes, later dismissed

2021-12-13 12:21 UTC, ddshcharbunou approved these changes, later dismissed

2021-12-13 12:59 UTC, Vladonblch submitted a review, later dismissed

2021-12-17 02:44 UTC, rakovets requested changes
Need refactor for the new project structure

2022-02-19 03:52 UTC, merged