Added hibernate-manual directori and AsciiDoc files
rakovets/workshop-asciidoc pull request #32
Opened 2021-12-12 23:07 UTC by alexkoval6030

2021-12-13 07:49 UTC, evzhigalko requested changes
1. Почистить от лишних файлов
2. добавить ссылки в index.adoc
3. Исправить однотипные ошибки, элементы кода , названия, классов, интерфейсов, методов и т.д. нужно оформлять через \`\`
Примеры ошибок обозначил , просмотри весь код, там одинаковые ошибки

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/nativeSQL.adoc
> +Таким обращом наше приложение создаст нативный SQL – запрос, испоьзуя метод *createSQLQuery()* интерфейса *Session*, который выглядит следующим образом:
1. элемент кода стоит оформить не жирным выделением, а через \`createSQLQuery()\`
2. тоже самое \`Session\`

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/nativeSQL.adoc
> +После того, как мы передаём методу *createSQLQuery()* строку (String), содержащую SQL – запрос, мы можем связать результат этого запроса с сохраняемым объектом (persistent object).
тоже самое \`createSQLQuery()\`

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/nativeSQL.adoc
> +Шаг 1. Создадим таблицу в нашей БД
задание: заменить текст ссылающий на последующую таблицу/изображение/код/команду на заголовок к этому блоку (Block title).
стоит сделать к примеру \.Шаг 1. Создадим таблицу в нашей БД

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/nativeSQL.adoc
> +*Developer.java*
элемент кода стоит оформлять так \`Developer.java\`

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/queriesUsingCriteria.adoc
> +Для создания *Criteria* используется метод createCriteria() интерфейса Session.
\`createCriteria()\`

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/queriesUsingCriteria.adoc
> +*public Criteria setFirstResult(int firstResult)*
оформить как блок кода java

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/queriesUsingCriteria.adoc
> +*public Criteria setMaxResults(int maxResults)*
оформить как блок кода java

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/queriesUsingCriteria.adoc
> +Шаг 1. Создадим таблицу HIBERNATE_DEVELOPERS в нашей БД.
задание: заменить текст ссылающий на последующую таблицу/изображение/код/команду на заголовок к этому блоку (Block title).
стоит сделать \.Шаг 1. Создадим таблицу HIBERNATE_DEVELOPERS в нашей БД.

2021-12-13 07:49 UTC, evzhigalko commented on hibernate-manual/queriesUsingCriteria.adoc
> +*Developer.java*
добавить \`Developer.java\`

2021-12-13 12:08 UTC, skarmyzov approved these changes, later dismissed

2021-12-17 02:45 UTC, rakovets requested changes
Need refactor for the new project structure

2022-01-08 10:32 UTC, alexkoval6030 commented
close: #47

2022-01-10 02:36 UTC, rakovets approved these changes
Approved

2022-01-10 02:37 UTC, merged