Feauture karpovich
rakovets/workshop-asciidoc pull request #33
Opened 2021-12-12 23:39 UTC by sablayz

https://proselyte.net/tutorials/hibernate-tutorial/mapping-files/
Please check.

2021-12-13 11:21 UTC, AleksandrTolkach commented on index.adoc
> -= Theme
Я бы тему вписал.

2021-12-13 11:21 UTC, AleksandrTolkach approved these changes, later dismissed
Ок

2021-12-13 12:07 UTC, skarmyzov submitted a review, later dismissed

2021-12-17 02:46 UTC, rakovets requested changes
Need refactor for the new project structure

2022-02-19 03:53 UTC, merged