Feature paramonov
rakovets/workshop-asciidoc pull request #40
Opened 2021-12-13 12:46 UTC by ben4a1

2021-12-13 13:55 UTC, evzhigalko reviewed
1. ошибка однотипная, шаги лучше через заголовки 2 уровня сделать 
2. элементы кода через \`\`
3. добавь ссылки на таблицы

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/many-to-one-mapping-example.adoc
> +Шаг 1. Создадим две таблицы в нашей базе данных (далее – БД)
здесь лучше как подзаголовок 2 уровня сделать либо через названия блока \.Шаг 1. Создадим две таблицы в нашей базе данных (далее – БД)

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/many-to-one-mapping-example.adoc
> +Шаг 2. Создадим POJO – классы
подзаголовок 2 уровня

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/many-to-one-mapping-example.adoc
> +*Developer.java*
здесь нужно оформить как элемент кода , через \`\`   пример: \`Developer.java\`

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/many-to-one-mapping-example.adoc
> +*Company.java*
добавь \`\`

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/one-to-one-mapping-example.adoc
> +Шаг 1. Создадим две таблицы в нашей базе данных (далее – БД)
лучше использовать подзаголовки 2 уровня

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/one-to-one-mapping-example.adoc
> +*Developer.java*
добавь \`Developer.java\` вместо жирного выделения

2021-12-13 13:55 UTC, evzhigalko commented on feature-paramonov/ hibernate-manual--relationship-types/one-to-one-mapping-example.adoc
> +*Developer.hbm.xml*
вместо жирного лучше \`\`

2021-12-17 02:47 UTC, rakovets requested changes
Need refactor for the new project structure

2022-01-09 12:20 UTC, closed without merging