spring-introduction / Ekaterina Komleva
rakovets/workshop-asciidoc pull request #68
Opened 2022-09-22 16:16 UTC by KateKoml

2022-09-22 17:14 UTC, Dzmitry-Highlander requested changes
Need to delete documentation and README.adoc

2022-09-22 17:21 UTC, Dzmitry-Highlander requested changes

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +Spring один из самых популярных фреймворков для J2EE. Разработчики по всему миру используют Spring для создания надёжных и качественных приложений. Он был разработан в Июне 2003 года Родом Джонсоном.
personal pronouns

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +Dependency Injection (DI) – один из видов инверсии управления (Inversion of Control – IoC). При написании действительно крупных и сложных проектов разработчики сталкиваются с необходимостью делать кл
bold

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +Dependency Injection – это ситуация, когда внедряется элемент одного класса в другой (конкретные примеры будут приведены позже). На практике DI осуществляется путём передачи параметров конструктора и
bold

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +На этом завершается вводная часть руководства по Spring. В следующей части будет рассмотрено, как создать простое Spring приложение с помощью IDE Intellij Idea.
delete, because it isn't an article! It is WIKI

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +Это руководство предназначено для Java разработчиков, которые хотят детально понять Spring Framework, его архитектуру и конкретное применение.
Delete, it is WIKI

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +== Необходимые знания
No need in this

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +Хорошее понимание Java Core и опыт работы с Intellij Idea.
No need in this

2022-09-22 17:21 UTC, Dzmitry-Highlander commented on spring/intro.adoc
> +Spring также включает в себя ряд других важных модулей, таких как AOP, Aspects, Instrumentation, Messaging и Test.
Maybe bold?

2022-09-23 05:14 UTC, rakovets requested changes
* Вернуть файлы: README, Technacal specification
* Исправить приведенные замечания И АНАЛОГИЧНЫЕ, не бойтесь использовать чаще ** для выделения недавно введеных названий и терминов а не __

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +*Dependency Injection* (DI) – один из видов инверсии управления (Inversion of Control – IoC). При написании действительно крупных и сложных проектов разработчики сталкиваются с необходимостью делать
```suggestion
*Dependency Injection* (*DI*) – один из видов *инверсии управления* (*Inversion of Control*/ *IoC*). При написании действительно крупных и сложных проектов разработчики сталкиваются с необходимостью делать классы приложения как можно более независимыми друг от друга для возможности повторного использования и unit-тестирования. Именно *DI* устанавливает связи между этими классами, при этом сохраняя их независимость друг от друга.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +Dependency Injection – это ситуация, когда внедряется элемент одного класса в другой (конкретные примеры будут приведены позже). На практике DI осуществляется путём передачи параметров конструктора и
```suggestion
*Dependency Injection* – это ситуация, когда внедряется элемент одного класса в другой (конкретные примеры будут приведены позже). На практике *DI* осуществляется путём передачи параметров конструктора или с помощью setters.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +Другим ключевым компонентом Spring является *Аспекто-ориентированное программирование* (_Aspect oriented programming – AOP_). Это функции, которые охватывают несколько узлов приложения, называются *c
```suggestion
Другим ключевым компонентом Spring является *Аспекто-ориентированное программирование* (*Aspect oriented programming*/ *AOP*). Это функции, которые охватывают несколько узлов приложения, называются *cross-cutting concerns*, и эти *cross-cutting concerns* отделены от непосредственной бизнес-логики приложения.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +В ООП ключевой единицей является класс, в то время, как в АОП ключевым элементом является аспект. DI помогает разделить классы приложения на отдельные модули, и АОП – помогает отделить cross-cutting
```suggestion
В *ООП* ключевой единицей является класс, в то время, как в *АОП* ключевым элементом является аспект. *DI* помогает разделить классы приложения на отдельные модули, и *АОП* – помогает отделить *cross-cutting concerns* от объектов, на которые они влияют.

 На данный момент *Spring* разделён на некоторое количество отдельных модулей, что позволяет разработчикум решать, какие из них использовать в приложении.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +*Основной контейнер* (_Core Container_) включает в себя Beans, Core, Context и SpEL (expression language).
```suggestion
*Основной контейнер* (*Core Container*) включает в себя *Beans*, *Core*, *Context* и *SpEL* (*expression language*).
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +* _Beans_ отвечает за BeanFactory которая является сложной реализацией паттерна Фабрика (GoF).
```suggestion
* *Beans* отвечает за `BeanFactory` которая является сложной реализацией _паттерна Фабрика (GoF)_.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +* Модуль _Core_ обеспечивает ключевые части фреймворка, включая свойства IoC и DI.
```suggestion
* Модуль *Core* обеспечивает ключевые части фреймворка, включая свойства *IoC* и *DI*.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +Контейнер *Data Access/Integration* состоит из JDBC, ORM, OXM, JMS и модуля Transactions.
```suggestion
Контейнер *Data Access*/*Integration* состоит из *JDBC*, *ORM*, *OXM*, *JMS* и модуля *Transactions*.
```

2022-09-23 05:14 UTC, rakovets commented on spring/intro.adoc
> +*Spring* также включает в себя ряд других важных модулей, таких как AOP, Aspects, Instrumentation, Messaging и Test.
```suggestion
*Spring* также включает в себя ряд других важных модулей, таких как *AOP*, *Aspects*, *Instrumentation*, *Messaging* и *Test*.
```

2022-09-23 08:02 UTC, rakovets requested changes
Need to fix

2022-09-23 08:02 UTC, rakovets commented on spring/intro.adoc
> +image::spring-framework.jpg[Архитектура Spring Framework]
```suggestion
== Архитектура Spring Framework

image::spring-framework.jpg[Архитектура Spring Framework]
```

2022-09-23 08:11 UTC, rakovets approved these changes

2022-09-23 14:26 UTC, SvetaPiven approved these changes
Good work💣

2022-09-23 14:27 UTC, Dzmitry-Highlander approved these changes

2022-09-23 14:29 UTC, merged