create-simple-application / Dzmitry Krasiuk
rakovets/workshop-asciidoc pull request #69
Opened 2022-09-22 17:03 UTC by Dzmitry-Highlander

2022-09-22 20:22 UTC, KateKoml commented on create-simple-application/page1.adoc
> +который как некая связующая смесь соединяет все компоненты программы в
punctuation mistake

2022-09-22 22:11 UTC, SvetaPiven reviewed
fix it

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +Далее следует метод *getBean()* этого контекста.
extraction of extraneous characters

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +*API ClassPathXmlApplicationContext()*.
extraction of extraneous characters

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +и создаёт и инициализирует все *beans* внутри этого файла. +
Incorrect selection

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +который как некая связующая смесь соединяет все компоненты программы в
exactly?

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +Комбинация клавиш для запуска программы *Alt + Shift + F10*, после нажатия
Incorrect selection

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +* Библиотеки автоматически включенные в проект
where is the end of the article? (В этом туториале мы создали приложение, используя технологию Spring. Конечно, для приложения такого уровня подключать Spring не имеет смысла, но это отправная точка, чтобы понять более сложные примеры)

2022-09-22 22:11 UTC, SvetaPiven commented on create-simple-application/page1.adoc
> +Далее следует метод *getBean()* этого контекста.
When mentioning a function/method, do not use ()

2022-09-23 06:48 UTC, KateKoml commented on create-simple-application/page1.adoc
> +который как некая связующая смесь соединяет все компоненты программы в
"который, как некая связующая смесь, соединяет все компоненты"

2022-09-23 13:29 UTC, KateKoml submitted a review, later dismissed

2022-09-23 14:37 UTC, rakovets requested changes

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +и создаёт и инициализирует все *beans* внутри этого файла. +
```suggestion
Создание контекста происходит с помощью *API* `ClassPathXmlApplicationContext()`. Это *API* загружает конфигурационный файл `spring-hello-bean.xml` и создаёт и инициализирует все *beans* внутри этого файла.
```

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +Этот метод принимает в качестве аргумента *bean ID*.
```suggestion
Далее следует метод `getBean()` этого контекста. Этот метод принимает в качестве аргумента *bean ID*.
```

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +image::spring-hello-bean-xml.webp[XML connection for elements]
```suggestion
.`spring-hello-bean.xml`
image::spring-hello-bean-xml.webp[XML connection for elements]
```

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +`Enter` вывод будет:
```suggestion
_Enter_ вывод будет:
```

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +Комбинация клавиш для запуска программы `Alt + Shift + F10`, после нажатия
```suggestion
Комбинация клавиш для запуска программы _Alt + Shift + F10_, после нажатия
```

2022-09-23 14:37 UTC, rakovets commented on index.adoc
> +include::create-simple-application/page1.adoc[leveloffset=1]
```suggestion
include::spring/create-simple-application.adoc[leveloffset=1]
```

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +image::spring-hello-world-java.webp[SpringHelloWorld.java]
```suggestion
.`SpringHelloWorld.java`
image::spring-hello-world-java.webp[SpringHelloWorld.java]
```

2022-09-23 14:37 UTC, rakovets commented on create-simple-application/page1.adoc
> +image::spring-hello-world-runner-java.webp[SpringHelloWorldRunner.java]
```suggestion
.`SpringHelloWorldRunner.java`
image::spring-hello-world-runner-java.webp[SpringHelloWorldRunner.java]
```

2022-09-23 16:30 UTC, KateKoml submitted a review, later dismissed

2022-09-23 17:03 UTC, SvetaPiven approved these changes
good work @Dzmitry-Highlander

2022-09-23 17:03 UTC, SvetaPiven commented on spring/create-simple-application.adoc
> +
```suggestion

```

2022-09-23 17:04 UTC, KateKoml approved these changes, later dismissed

2022-09-23 17:04 UTC, SvetaPiven submitted a review, later dismissed
yessss

2022-09-26 09:33 UTC, rakovets requested changes
Выправіць вось гэта і будзе гатова да мерджу

2022-09-26 09:33 UTC, rakovets commented on spring/create-simple-application.adoc
> +Далее следует метод `getBean()` этого контекста. Этот метод принимает в качестве аргумента *bean ID*.
```suggestion
Создание контекста происходит с помощью *API* `ClassPathXmlApplicationContext()`. Это *API* загружает конфигурационный файл `spring-hello-bean.xml` и создаёт и инициализирует все *beans* внутри этого файла.

Далее следует метод `getBean()` этого контекста. Этот метод принимает в качестве аргумента *bean ID*.
```

2022-09-26 09:33 UTC, rakovets commented on spring/create-simple-application.adoc
> +один исправный механизм.
```suggestion
Главным звеном этого приложения является именно `spring-hello-bean.xml`, который, как некая связующая смесь соединяет все компоненты программы в один исправный механизм.
```

2022-09-26 09:33 UTC, rakovets commented on spring/create-simple-application.adoc
> +_Enter_ вывод будет:
```suggestion
Комбинация клавиш для запуска программы _Alt + Shift + F10_, после нажатия _Enter_ вывод будет:
```

2022-09-26 17:17 UTC, KateKoml approved these changes

2022-09-26 17:18 UTC, SvetaPiven approved these changes

2022-09-26 18:12 UTC, rakovets approved these changes

2022-09-27 04:12 UTC, merged