feat: creating new documentation JavaPassingParametrs.adoc / Sveta Piven
rakovets/workshop-asciidoc pull request #70
Opened 2022-09-22 18:17 UTC by SvetaPiven

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Многие программисты часто путают, какие параметры в Java передаются по значению, а какие по ссылке. Давайте визуализируем этот процесс, и тогда вы увидите насколько все просто.
Use of pronouns

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +В программе, приведенной выше, список _fruits_ передается методу *processData*. Переменная _fruitRef_ — это копия параметра _fruit_. И _fruits_ и _fruitsRef_ размещаются в стеке. Это две разные ссылк
Use of pronouns

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Итак, Java всегда передает параметры по значению. Однако мы должны быть осторожны при передаче ссылок на объекты.
Use of pronouns

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +   Node(int d){
Code Convention

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +       if (head == null){
Code Convention

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +   if (head == null){
Code Convention

2022-09-22 20:22 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +В этой статье мы обсудили одну небольшую, но важную концепцию Java: передачу параметров.
remove non-essential text

2022-09-22 20:46 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Многие программисты часто путают, какие параметры в Java передаются по значению, а какие по ссылке. Давайте визуализируем этот процесс, и тогда вы увидите насколько все просто.
bugs fixed

2022-09-22 20:47 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +В программе, приведенной выше, список _fruits_ передается методу *processData*. Переменная _fruitRef_ — это копия параметра _fruit_. И _fruits_ и _fruitsRef_ размещаются в стеке. Это две разные ссылк
bugs fixed

2022-09-22 20:48 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Итак, Java всегда передает параметры по значению. Однако мы должны быть осторожны при передаче ссылок на объекты.
bugs fixed

2022-09-22 20:48 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +   Node(int d){
bugs fixed

2022-09-22 20:48 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +       if (head == null){
bugs fixed

2022-09-22 20:48 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +   if (head == null){
bugs fixed

2022-09-22 20:48 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +В этой статье мы обсудили одну небольшую, но важную концепцию Java: передачу параметров.
bugs fixed

2022-09-23 04:22 UTC, Dzmitry-Highlander requested changes

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +. *Передача по значению (by value).* Значения фактических параметров копируются.
incorrect selection: dot

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Блог компании OTUS , Программирование , Java
delete: Wiki, not a blog

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +. *Передача по ссылке (by reference).* Параметры передаются как ссылка (адрес) на исходную переменную.
incorrect selection: dot

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +. Локальные переменные, такие как примитивы и ссылки на объекты, создаются в стеке.
(stack)

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Теперь вернемся к основному вопросу: переменные передаются по значению или по ссылке?
delete: not necessary for Wiki

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Чтобы разобраться с этим, давайте посмотрим на пример.
delete: not necessary for Wiki

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Поскольку Java передает параметры по значению, метод `processData` работает с копией данных.
add: () for method

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Следовательно, в исходных данных (в методе `main`) не произошло никаких изменений.
add: () for method

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Чтобы с этим разобраться, давайте посмотрим на следующую диаграмму.
delete: not necessary for Wiki

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Нет, неправильно.
delete: not necessary for Wiki

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +В программе, приведенной выше, список `fruits` передается методу `processData`.
add: () for method

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Переменная `fruitRef` — это копия параметра `fruit`.
better use BOLD

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Но самое интересное заключается в том, что они *указывают на один и тот же объект* в куче.
(heap)

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +class Node {
code convetion: var names

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Это решение работает во всех случаях, кроме одного — когда вы удаляете первый узел (`Position = 1`).
personal pronounce

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Основываясь на ранее описанной концепции, видите ли вы в чем здесь проблема?
personal pronounce

2022-09-23 04:22 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Возможно, поможет следующая диаграмма.
Wiki, not article

2022-09-23 07:48 UTC, SvetaPiven commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Переменная `fruitRef` — это копия параметра `fruit`.
I don't agree

2022-09-23 07:51 UTC, KateKoml commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +. Локальные переменные, такие как примитивы и ссылки на объекты, создаются в stack.
```suggestion
. Локальные переменные, такие как примитивы и ссылки на объекты, создаются в *stack*.
. Объекты в *heap*.
```

2022-09-23 08:22 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +class Node {
Это чужой код из статьи, поэтому лучше без изменений

2022-09-23 08:31 UTC, rakovets requested changes
* выдаліць малюнак які дубліруе імя тэмы
* даць назву файлам ў стылі `lower-kebab-case`
* даць назвы малюнкам, якія адлюструюць тое, што на іх знаходзіцца

2022-09-23 08:31 UTC, rakovets commented on .gitignore
> +feature-${surname}# Compiled class file
Што гэта?

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> += _Java: передача параметров по значению или по ссылке_
```suggestion
= Передача параметров по значению или по ссылке
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +
```suggestion
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +
```suggestion
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Визуализируем этот процесс и увидим насколько все просто.
Лепей адзін абзац рабіць у адзін радок і налаштаваць гэта ў IDE, каб рабіла soft-wrape

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +[source, java]
```suggestion
.Удаление узла в связанном списке
[source, java]
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +====
```suggestion
image::single-linked.png[Удаление узла в связанном списке]
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +class LinkedList {
```suggestion
}
----

[source, java]
----
class LinkedList {
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +    public static void deleteNode(Node head, int position) {
```suggestion
    }
    
    public static void deleteNode(Node head, int position) {
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +    public static void printList(Node head) {
```suggestion
    }
    
    public static void printList(Node head) {
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +    public static void main(String[] args) {
```suggestion
    }
    
    public static void main(String[] args) {
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +    public static void main(String[] args) {
```suggestion
    }
    
    public static void main(String[] args) {
```

2022-09-23 08:31 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +---
```suggestion
```

2022-09-23 08:31 UTC, rakovets commented on index.adoc
> += Java Passing Parametrs!
```suggestion
= Java
```

2022-09-23 08:31 UTC, rakovets commented on index.adoc
> +Wiki for 'JavaPassingParametrs'.
```suggestion
Wiki for 'Java'.
```

2022-09-23 08:31 UTC, rakovets commented on index.adoc
> +include::JavaPassingParametrs/JavaPassingParametrs.adoc[leveloffset=1]
```suggestion
include::java/passing-parametrs.adoc[leveloffset=1]
```

2022-09-23 08:44 UTC, SvetaPiven commented on .gitignore
> +feature-${surname}# Compiled class file
случайно вставилось наверное когда в терминал писала)

2022-09-23 13:31 UTC, KateKoml submitted a review, later dismissed

2022-09-23 14:32 UTC, Dzmitry-Highlander requested changes
refactor: do in WIKI style

2022-09-23 14:44 UTC, rakovets requested changes

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +[source, java]
```suggestion
----

[source, java]
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Следовательно, изменения, сделанные в вызываемом методе, также будут отражены в исходном значении.
```suggestion
. Передача по ссылке (*by reference*). Параметры передаются как ссылка (адрес) на исходную переменную. Вызываемый метод не создает свою копию, а ссылается на исходное значение. Следовательно, изменения, сделанные в вызываемом методе, также будут отражены в исходном значении.
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +
```suggestion
----
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +.Удаление первого узла односвязного списка
```suggestion

.Удаление первого узла односвязного списка
image::stack-heap-deleted-fitst-node.png[Удаление первого узла односвязного списка]

```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +
```suggestion

.Удаление узла в связанном списке
image::deleted-single-linked.png[Удаление узла в связанном списке]

```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Однако необходимо быть осторожными при передаче ссылок на объекты.
```suggestion
Java всегда передает параметры по значению. Однако необходимо быть осторожными при передаче ссылок на объекты.
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +.Память stack и кучи heap
```suggestion

.Передача объекта по ссылке
image::example3.png[Передача объекта по ссылке]

.Память stack и кучи heap
image::stack-heap-operator-new.png[Память stack и heap]

```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Теперь `fruitRef` указывает на новый объект, и, следовательно, любые изменения, которые вносим в него, не повлияют на исходный объект списка фруктов.
```suggestion
В этом случае для изменения ссылки `fruitRef` используем оператор `new`. Теперь `fruitRef` указывает на новый объект, и, следовательно, любые изменения, которые вносим в него, не повлияют на исходный объект списка фруктов.
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +.Память stack и heap +
```suggestion

.Память stack и heap
image::example-passing-an-object-by-reference.png[Память stack и heap]

```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +.Передача объекта +
```suggestion

.Передача объекта
image::example-passing-an-object.png[Передача объекта по ссылке]

```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +.Пример передачи примитивов по значению
```suggestion

.Пример передачи примитивов по значению
image::example-parameters-by-value.png[Передача объекта]

```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Следовательно, в исходных данных (в методе `main()`) не произошло никаких изменений.
```suggestion
Поскольку Java передает параметры по значению, метод `processData()` работает с копией данных. Следовательно, в исходных данных (в методе `main()`) не произошло никаких изменений.
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +То есть, любое изменение, которое будет внесено с помощью любой из этих ссылок, влияет на объект.
```suggestion
В программе, приведенной выше, список `fruits` передается методу `processData()`.
Переменная `fruitRef` — это копия параметра `fruit`. И `fruits` и `fruitsRef` размещаются в стеке.
Это две разные ссылки. Но самое интересное заключается в том, что они *указывают на один и тот же объект* в heap. То есть, любое изменение, которое будет внесено с помощью любой из этих ссылок, влияет на объект.
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +Есть два способа передачи параметров:
```suggestion
Данные передаются между методами через параметры. Есть два способа передачи параметров:
```

2022-09-23 14:44 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +. Передача по ссылке (*by reference*). Параметры передаются как ссылка (адрес) на исходную переменную.
```suggestion
1. Передача по значению (*by value*). Значения фактических параметров копируются. Вызываемый метод создает свою копию значений аргументов и затем ее использует. Поскольку работа ведется с копией, на исходный параметр это никак не влияет.
2. Передача по ссылке (*by reference*). Параметры передаются как ссылка (адрес) на исходную переменную.
```

2022-09-23 14:48 UTC, rakovets commented
> refactor: do in WIKI style

Не нужно полностью переосмыслівать текст, главное ізбавітся от воды і слов связок :) Он будет еще не раз переработан, перед тем как попадет в вики.

2022-09-23 16:24 UTC, Dzmitry-Highlander requested changes

2022-09-23 16:24 UTC, Dzmitry-Highlander commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +.Пример передачи примитивов по значению
add: \:

2022-09-23 16:31 UTC, KateKoml approved these changes, later dismissed

2022-09-23 16:51 UTC, Dzmitry-Highlander approved these changes

2022-09-23 16:53 UTC, Dzmitry-Highlander commented on index.adoc
> +include::JavaPassingParametrs/passing-parametrs.adoc[leveloffset=1]
```suggestion
include::JavaPassingParametrs/passing-parametrs.adoc[leveloffset=1]
```
include::spring/passing-parametrs.adoc[leveloffset=1]

2022-09-23 17:01 UTC, Dzmitry-Highlander approved these changes, later dismissed

2022-09-23 19:58 UTC, KateKoml approved these changes, later dismissed

2022-09-24 10:40 UTC, KateKoml approved these changes, later dismissed

2022-09-24 14:44 UTC, Dzmitry-Highlander approved these changes, later dismissed
OK

2022-09-25 07:21 UTC, rakovets requested changes
* Title для малюнкаў павіннен знаходзіцца каля іх
* Не зменена назва дэрыкторыі для топіка. Па такой логіцы як зараз: новы топік - новая дэрыкторыя - новы файл у ёй які дублюе яе імя?
* дэрыкторыю назваць `java`, а файл у ёй `passing-parameters.adoc`

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::deleted-single-linked.png[Удаление узла в связанном списке]
```suggestion
.Удаление узла в связанном списке
image::deleted-single-linked.png[Удаление узла в связанном списке]
```

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::stack-heap-operator-new.png[Память stack и heap]
```suggestion
.Память stack и heap
image::stack-heap-operator-new.png[Память stack и heap]
```

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::example-passing-an-object-by-reference.png[Передача объекта по ссылке]
```suggestion
.Передача объекта по ссылке
image::example-passing-an-object-by-reference.png[Передача объекта по ссылке]
```

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::example-passing-an-object.png[Передача объекта по ссылке]
```suggestion
.Передача объекта +
image::example-passing-an-object.png[Передача объекта по ссылке]
```

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::example-passing-an-object-by-reference.png[Память stack и heap]
```suggestion
.Память stack и heap +
image::example-passing-an-object-by-reference.png[Память stack и heap]
```

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::example-parameters-by-value.png[Передача объекта]
```suggestion
.Пример передачи примитивов по значению:
image::example-parameters-by-value.png[Передача объекта]
```

2022-09-25 07:21 UTC, rakovets commented on JavaPassingParametrs/JavaPassingParametrs.adoc
> +image::stack-heap-deleted-fitst-node.png[Удаление первого узла односвязного списка]
```suggestion
.Удаление первого узла односвязного списка
image::stack-heap-deleted-fitst-node.png[Удаление первого узла односвязного списка]
```

2022-09-25 08:33 UTC, KateKoml submitted a review, later dismissed

2022-09-25 18:45 UTC, Dzmitry-Highlander approved these changes, later dismissed

2022-09-26 09:29 UTC, rakovets commented
@SvetaPiven Не выпраўдены маі заўвагі.

2022-09-26 09:30 UTC, rakovets commented
@KateKoml @Dzmitry-Highlander таксама глядзіце на заўвагі іншых і ці выпраўляюць іх

2022-09-26 09:30 UTC, rakovets requested changes
Усё яшчэ не выпраўлены заўвагі

2022-09-26 12:33 UTC, KateKoml submitted a review, later dismissed
ok

2022-09-27 03:56 UTC, rakovets submitted a review, later dismissed

2022-09-27 03:59 UTC, rakovets commented
@SvetaPiven @KateKoml @Dzmitry-Highlander зрабіў невялікія выпраўленні, паглядзіце па камміту якія. Некаторыя з іх дастаткова не відавочныя, а на вопыце падтрымкі кода.

@SvetaPiven вырашы merge-conflicts і я гатовы паставіць approve

2022-09-27 04:25 UTC, Dzmitry-Highlander submitted a review, later dismissed

2022-09-27 05:40 UTC, Dzmitry-Highlander approved these changes, later dismissed

2022-09-27 13:01 UTC, KateKoml approved these changes, later dismissed

2022-09-28 02:59 UTC, rakovets requested changes

2022-09-28 02:59 UTC, rakovets commented on index.adoc
> +
Ммм, што гэта за merge.
Merge павінен з'яднаць код, каб пасля яго ён працаваў і выглядаў адэкватна, а не проста зклеіць :)

2022-09-28 02:59 UTC, rakovets commented on index.adoc
> +
```suggestion
= Java

:source-highlighter: prettify
:sectnums:
:toc: left
:toclevels: 2

:toc!:

Wiki for 'Java'.

include::java/passing-parameters.adoc[leveloffset=1]

include::spring/intro.adoc[leveloffset=1]

include::spring/create-simple-application.adoc[leveloffset=1]

```

2022-09-28 03:17 UTC, SvetaPiven commented on index.adoc
> +
извиняюся)))

2022-09-28 17:51 UTC, KateKoml approved these changes, later dismissed

2022-09-30 05:13 UTC, rakovets submitted a review, later dismissed

2022-09-30 05:14 UTC, rakovets commented
Можна мержыць без пацверджання ад Дзмітрыя

2022-09-30 15:17 UTC, merged