feat: add topic 5 as AsciiDoc page
rakovets/workshop-asciidoc pull request #71
Opened 2022-09-23 14:04 UTC by Dzmitry-Highlander

<html>
<body>

https://proselyte.net/spring-tutorial-full-version/introduction-into-beans/
--

</body>
</html>

2022-09-23 14:12 UTC, KateKoml approved these changes, later dismissed

2022-09-23 16:34 UTC, KateKoml commented on index.adoc
>  Wiki for 'Example'.
Wiki for 'Spring'

2022-09-23 17:17 UTC, KateKoml submitted a review, later dismissed

2022-09-24 09:21 UTC, SvetaPiven approved these changes, later dismissed
great)

2022-09-27 04:14 UTC, rakovets requested changes

2022-09-27 04:14 UTC, rakovets commented on index.adoc
> +include::spring/introduction-into-beans.adoc[leveloffset=1]
```suggestion
include::spring/intro.adoc[leveloffset=1]

include::spring/introduction-into-beans.adoc[leveloffset=1]
```

2022-09-27 04:14 UTC, rakovets commented on spring/introduction-into-beans.adoc
> +.XML
```suggestion
```

2022-09-27 04:14 UTC, rakovets commented on spring/introduction-into-beans.adoc
> +image::xml-config.webp[Пример конфигурации]
```suggestion
.`xml-config.xml`
image::xml-config.webp[Пример конфигурации]
```

2022-09-27 04:14 UTC, rakovets commented on spring/introduction-into-beans.adoc
> +''''
```suggestion
```

2022-09-27 04:14 UTC, rakovets commented on spring/introduction-into-beans.adoc
> +''''
Не патрэбна паўтараць нейкія фішкі дызайну аўтара

2022-09-27 04:14 UTC, rakovets commented on spring/introduction-into-beans.adoc
> +а не при запуске приложения.
```suggestion
* *class* +
Этот атрибут является обязательным и указывает конкретный класс Java-приложения, который будет использоваться для создания *bean*.

* *name* +
Определяет области видимости создаваемых объектов.

* *constructor-arg* +
Определяет конструктор, использующийся для внедрения зависимости.

* *properties* +
Определяет свойства внедрения зависимости.

* *initialization method* +
Определяет метод инициализации *bean*.

* *destruction method* +
Определеят метод уничтожения *bean*, который будет использоваться при уничтожении контейнера, содержащего *bean*.

* *autowiring mode* +
Определяет режим автоматического связывания при внедрении зависимости.

* *lazy-initialization mode* +
Режим ленивой инициализации даёт контейнеру *IoC* команду создавать экземпляр бина при первом запросе, а не при запуске приложения.
```

2022-09-27 04:14 UTC, rakovets commented on spring/introduction-into-beans.adoc
> +'''''
```suggestion
```

2022-09-27 04:36 UTC, rakovets approved these changes

2022-09-27 04:36 UTC, rakovets commented
need to resolve merge-conflict

2022-09-27 05:36 UTC, SvetaPiven approved these changes, later dismissed

2022-10-02 03:28 UTC, rakovets approved these changes, later dismissed

2022-10-02 18:54 UTC, KateKoml approved these changes, later dismissed

2022-10-03 05:49 UTC, KateKoml approved these changes

2022-10-09 15:35 UTC, SvetaPiven approved these changes

2022-10-10 10:27 UTC, rakovets approved these changes

2023-01-31 22:05 UTC, closed without merging