feat: add topic 4 as AsciiDoc page
rakovets/workshop-asciidoc pull request #73
Opened 2022-09-23 16:29 UTC by KateKoml

2022-09-23 17:08 UTC, Dzmitry-Highlander submitted a review, later dismissed

2022-09-24 09:48 UTC, SvetaPiven commented on Spring/ioc-containers.adoc
> +image::project structure.jpg[Структура проекта]
```suggestion
дать названия новым файлам в стиле lower-kebab-case
```

2022-09-24 09:48 UTC, SvetaPiven commented on Spring/ioc-containers.adoc
> +image::project structure2.jpg[Структура проекта]
```suggestion
image::project-structure2.jpg[Структура проекта]
```

2022-09-24 09:48 UTC, SvetaPiven commented on Spring/ioc-containers.adoc
> +. *Spring BeanFactory Container*;
```suggestion
. *Spring `BeanFactory` Container*;
```

2022-09-24 09:48 UTC, SvetaPiven commented on Spring/ioc-containers.adoc
> +. *Spring ApplicationContext Container*;
```suggestion
. *Spring `ApplicationContext` Container*;
```

2022-09-24 10:58 UTC, SvetaPiven submitted a review, later dismissed

2022-09-24 11:38 UTC, SvetaPiven approved these changes, later dismissed
good

2022-09-24 14:44 UTC, Dzmitry-Highlander approved these changes, later dismissed
OK

2022-09-27 04:07 UTC, rakovets requested changes

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +:imagesdir: ../assets/img/spring-ioc-containers
```suggestion
:imagesdir: ../assets/img/spring/ioc-containers
```

І не забывай змяніць назву дэрыкторыі

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> += Руководство по Spring. Введение. Контейнеры IoC.
```suggestion
= Введение. Контейнеры IoC.
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +. *Java код*.
```suggestion
1. *XML*
2. *Аннотации Java*
3. *Java код*
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +`Java POJO` классы поступает в *Spring Container*, который на основании инструкций, полученных через метаданные, выдаёт приложение, готовое к использованию.
```suggestion
Java *POJO* классы поступает в *Spring Container*, который на основании инструкций, полученных через метаданные, выдаёт приложение, готовое к использованию.
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +. *Spring* `ApplicationContext` *Container*;
```suggestion
1. `BeanFactory`
2. `ApplicationContext`
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +== Spring BeanFactory Container
```suggestion
== `BeanFactory`
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::project-structure.jpg[Структура проекта]
```suggestion
.Структура проекта
image::project-structure.jpg[Структура проекта]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::class-message.jpg[Класс Message.java]
```suggestion
.Класс `Message.java`
image::class-message.jpg[Класс Message.java]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::message-bean.jpg[Конфигурационный файл message-bean.xml]
```suggestion
.Конфигурационный файл `message-bean.xml`
image::message-bean.jpg[Конфигурационный файл message-bean.xml]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::messagerunner.jpg[Класс MessageRunnerWithBeanFactory.java]
```suggestion
.Класс `MessageRunnerWithBeanFactory.java`:
image::messagerunner.jpg[Класс MessageRunnerWithBeanFactory.java]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::result.jpg[Результат работы]
```suggestion
.Результат работы программы
image::result.jpg[Результат работы]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +== Spring ApplicationContext Container
```suggestion
== `ApplicationContext`
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +* `WebXmlApplicationContext`. Эта реализация `ApplicationContext` получает необходимую информацию из веб-приложения.
```suggestion
* `FileSystemXmlApplicationContext` +
Этот контейнер загружает данные о бине из XML файла. При использовании этой реализации в конструкторе необходимо указать полный адрес конфигурационного файла.
* `ClassPathXmlApplicationContext` +
Этот контейнер также получает данные о бине из XML файла. Но в отличие от `FileSystemApplicationContext`, в этом случае необходимо указать относительный адрес конфигурационного файла (*CLASSPATH*).
* `WebXmlApplicationContext` +
Эта реализация `ApplicationContext` получает необходимую информацию из веб-приложения.
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::project-structure2.jpg[Структура проекта]
```suggestion
.Структура проекта
image::project-structure2.jpg[Структура проекта]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::class-message2.jpg[Класс Message.java]
```suggestion
.Класс `Message.java`
image::class-message2.jpg[Класс Message.java]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::message-bean2.jpg[Конфигурационный файл message-bean.xml]
```suggestion
.Конфигурационный файл `message-bean.xml`
image::message-bean2.jpg[Конфигурационный файл message-bean.xml]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::messagerunner2.jpg[Класс MessageRunnerWithBeanFactory.java]
```suggestion
.Класс `MessageRunnerWithBeanFactory.java`
image::messagerunner2.jpg[Класс MessageRunnerWithBeanFactory.java]
```

2022-09-27 04:07 UTC, rakovets commented on spring/ioc-containers.adoc
> +image::result2.jpg[Результат работы]
```suggestion
.Результат работы программы
image::result2.jpg[Результат работы]
```

2022-09-28 05:19 UTC, SvetaPiven approved these changes, later dismissed

2022-09-30 15:04 UTC, SvetaPiven submitted a review, later dismissed

2022-10-02 03:27 UTC, rakovets requested changes
Патрэбна загрузіць малюнкі лепшай якасці, а не preview для іх

2022-10-02 03:27 UTC, rakovets commented on index.adoc
> +include::spring/ioc-containers.adoc[leveloffset=1]
```suggestion
include::spring/intro.adoc[leveloffset=1]

include::spring/create-simple-application.adoc[leveloffset=1]

include::spring/ioc-containers.adoc[leveloffset=1]
```

2022-10-02 03:45 UTC, Dzmitry-Highlander submitted a review, later dismissed

2022-10-09 14:09 UTC, Dzmitry-Highlander approved these changes, later dismissed

2022-10-09 15:34 UTC, SvetaPiven approved these changes, later dismissed

2022-10-10 10:27 UTC, rakovets submitted a review, later dismissed

2022-10-10 10:27 UTC, rakovets commented on index.adoc
> +
```suggestion

```

2022-10-10 10:47 UTC, SvetaPiven approved these changes, later dismissed

2022-10-10 11:01 UTC, SvetaPiven approved these changes

2022-10-10 16:41 UTC, rakovets approved these changes

2022-10-10 16:44 UTC, merged