feat: add topic 6 as AsciiDoc page
rakovets/workshop-asciidoc pull request #74
Opened 2022-09-24 08:01 UTC by SvetaPiven

2022-09-24 10:57 UTC, KateKoml commented on spring/springBin.adoc
> +При определении *bean* в Spring Framework, есть возможность объявить область видимости этого компонента.
```suggestion
При определении *bean* в *Spring Framework*, есть возможность объявить область видимости этого компонента.
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +Например, чтобы Spring возвращал нам один и тот же bean при каждом запросе, необходимо выбрать область видимости *singleton*.
```suggestion
Например, чтобы Spring возвращал нам один и тот же *bean* при каждом запросе, необходимо выбрать область видимости *singleton*.
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +При определении *bean* в Spring Framework, есть возможность объявить область видимости этого компонента.
```suggestion
При определении *bean* в *Spring Framework*, есть возможность объявить область видимости этого компонента.
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +В Spring Framework имеются пять возможных значений свойства scope:
```suggestion
В Spring Framework имеются пять возможных значений свойства *scope*:
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +Рассмотрим singleton и prototype.
```suggestion
Рассмотрим *singleton* и *prototype*.
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +.Класс Message.java
```suggestion
.Класс `Message.java`
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +.Класс MessageRunner.java
```suggestion
.Класс `MessageRunner.java`
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +.Класс Message.java
```suggestion
.Класс `Message.java`
```

2022-09-24 11:15 UTC, KateKoml commented on spring/springBin.adoc
> +.Класс MessageRunner.java
```suggestion
.Класс `MessageRunner.java`
```

2022-09-24 12:06 UTC, KateKoml approved these changes, later dismissed

2022-09-24 15:44 UTC, Dzmitry-Highlander approved these changes, later dismissed

2022-09-25 08:35 UTC, KateKoml approved these changes, later dismissed

2022-09-25 18:45 UTC, Dzmitry-Highlander submitted a review, later dismissed

2022-09-27 04:22 UTC, rakovets requested changes
* Якасць малюнкаў проста жахліваю. Патрэбна замяніць.

Для гэтага, выпампоўваць іх патрэбна не адразу, а адчыняць ТОЛЬКО малюнак у новай Tab  і толькі потым зпампоўваць. Гэта Web, тут шмат момантаў дзе спрабуюць паменшыць памеры старонкі, каб хутка грузілася і дзе ёсць магчымасць, калі патрэбна, дагрузіць нармальны малюнак :)

2022-09-27 04:22 UTC, rakovets commented on index.adoc
> +include::spring/springBin.adoc[leveloffset=1]
```suggestion
include::spring/spring-bean.adoc[leveloffset=1]
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> += Руководство по Spring. Область видимости beans.
```suggestion
= Область видимости beans.
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +---
```suggestion
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +Рассмотрим *singleton* и *prototype*.
```suggestion
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +Создаётся один экземпляр *bean* на каждую глобальную HTTP сессию. Касается исключительно `ApplicationContext`.
```suggestion
* *singleton* +
Определяет один единственный *bean* для каждого контейнера *Spring IoC* (используется по умолчанию).

* *prototype* +
Позволяет иметь любое количество экземпляров *bean*.

* *request* +
Создаётся один экземпляр *bean* на каждый HTTP запрос. Касается исключительно `ApplicationContext`.

* *session* +
Создаётся один экземпляр *bean* на каждую HTTP сессию. Касается исключительно `ApplicationContext`.

* *global-session* +
Создаётся один экземпляр *bean* на каждую глобальную HTTP сессию. Касается исключительно `ApplicationContext`.
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +.XML
```suggestion
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +</bean>
```suggestion
<bean id = "someBean" scope = "singleton">
    <!--some code to configure bean-->
</bean>
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +.XML
```suggestion
```

2022-09-27 04:22 UTC, rakovets commented on spring/springBin.adoc
> +</bean>
```suggestion
<bean id = "someBean" scope = "prototype">
    <!--some code to configure bean-->
</bean>
```

2022-09-27 05:40 UTC, Dzmitry-Highlander approved these changes, later dismissed

2022-10-02 03:25 UTC, rakovets approved these changes, later dismissed

2022-10-02 03:25 UTC, rakovets commented on index.adoc
> +
```suggestion
```

2022-10-02 03:44 UTC, Dzmitry-Highlander submitted a review, later dismissed

2022-10-02 14:35 UTC, rakovets approved these changes

2022-10-02 19:26 UTC, KateKoml approved these changes

2022-10-09 14:10 UTC, Dzmitry-Highlander approved these changes

2022-10-09 15:36 UTC, merged